### ISSUE TITLE
1.3.10 creates exe to be executed with admin privileges

### ISSUE THREAD

**Issue by IgorJorobus** [larsch/ocra#127]
This isn't a bug, just want to make you aware that in version 1.3.10 the executable gets built to be executed with admin privileges. This doesn't happen for version 1.3.9 under the same circunstances (platform & ruby version). Not a bug but not desired too.

Platform: Windows 10 Enterprise
Ruby: 2.3.3
Ocra: 1.3.10

**Comment by larsch** [comment]
Not able to reproduce. There doesn't seem to be any related changed from 1.3.9 to 1.3.10 that could cause this.

**Comment by KrzaQ** [comment]
This issue has repeatedly hit me in the past, and I did some sleuthing. It turns out that 1.3.10 had more changes than is apparent from the commit history, notably [replacing the `stub.exe` with a new one, created with a 32-bit compiler][1].

Unfortunately, this walks right into Windows's [Installer Detection Technology][2], which requires elevated privileges from 32-bit executables with names that include installer/update/setup - I believe the core usage for OCRA.

As a workaround, I tried replacing `stub.exe` with a copy from 1.3.9 and I can report a full success: it makes the OCRA-generated executables not require admin privileges again.

@larsch: a reproduction case (file naming is important)
`test_ocra_updater.rb`:
```rb
exit if defined?(Ocra)
puts "Hello, World!"
```
command line:
```cmd
ocra test_ocra_updater.rb --dll ruby_builtin_dlls/libgmp-10.dll --dll ruby_builtin_dlls/libssp-0.dll
test_ocra_updater.exe
```

[1]: https://github.com/larsch/ocra/commit/9c5fe287887f16db0c00ad54a549ff383f4c8d91#diff-32e8fc5a7a6b9f84aa338b60ba373fe810b64cd87c9c8f4743b807e4bfb4ab28R6-R7
[2]: https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-vista/cc709628(v=ws.10)?
