### ISSUE TITLE
Can't run exe

### ISSUE THREAD

**Issue by Matthiasclee** [larsch/ocra#152]
I made a ruby script and and ran ocra myscript.rb and got  myscript.exe but, when i run myscript.exe, i get FATAL ERROR: Bad signature in executable.

**Comment by circutrider21** [comment]
You Get This Error due to the fact that this executable wasn't signed. Usually executable that aren't signed are still allowed to run on your computer, but if the security settings on your computer are set to strict, then the executable will not run and will be treated like a virus. In conclusion exe files made with ocra aren't signed but should still work. Try fixing your settings and try again.

**Comment by larsch** [comment]
Indeed, OCRA executable does not contain signatures, but they should still work. I have to no idea what setting/software on your system could be causing the issue. Let me know if you have additional details.
