### ISSUE TITLE
Exe file name in the task manager instead of rubyw.exe or ruby.exe.

### ISSUE THREAD

**Issue by georgy7** [larsch/ocra#91]
For example, main.exe.
Is this possible? Maybe as a custom feature.
I did not find anything like this neither on its website nor in `--help`.

**Comment by larsch** [comment]
Not directly.

Since ocra just launces the packaged Ruby.exe, you can try copying or renaming it (e.g. to 'myruby.exe'), and add a line like this to your script:

```ruby
RbConfig::CONFIG['ruby_install_name'] = 'myruby'
```

But you will still see the two processes: the built .exe and the spawned myruby.exe.

Ideally, the executable you create with Ocra would contain an embedded Ruby interpreter which did all the work instead of launching a sub process. There are ways to do this, but I haven't researched them fully, and it's possible quite a bit of work to do.
