### ISSUE TITLE
OCRA creating gigs of temp files after each run.

### ISSUE THREAD

**Issue by predatorian3** [larsch/ocra#92]
I have a script that I'm using to pull values from a Windows program and report it for monitoring. However, OCRA is piling up temp files in C:\WINDOWS\Temp, and not deleting them after the run. Is it safe to delete these temp files, or should OCRA be taking care of that, or should I script it in my program?

**Comment by larsch** [comment]
Ocra attempts to delete the temporary folder created when it runs (usually named ocrXXXX). If you create other files in %TEMP%, or keep them open (e.g. by launching child processes) after ruby.exe exists, it will not be able to delete them properly if the files are still open. Virus scanners could also be interfering.

I guess we should have the standard workaround of trying repeatedly to delete the files for a while, if some program is keeping them open.

What is your program doing? Does it do stuff after ruby.exe is done?

**Comment by predatorian3** [comment]
The script executes a command line program for WebSphere MQ, and collects the output, filters through it to get a number, then reports it to Zabbix for trending. Then Exits.

**Comment by larsch** [comment]
I have reworked the temp file clean up in Ocra 1.3.6. It's now done manually instead of using the shell API. There's also now two fall back methods, MoveFileEx() and a custom method of leaving a .ocra-delete-me if the deletion fails. Next time the program is launched, it will clean up if possible. MoveFileEx() requires administrator privileges though.
